// 자동 생성된 국가 데이터 파일
export interface CountryInfo {
  countryKr: string;
  countryEn: string;
  capitalKr: string;
  capitalEn: string;
}

export const countryList: CountryInfo[] = [
  {
    countryKr: "가나",
    countryEn: "Ghana",
    capitalKr: "아크라",
    capitalEn: "Accra",
  },
  {
    countryKr: "가봉",
    countryEn: "Gabon",
    capitalKr: "리브르빌",
    capitalEn: "Libreville",
  },
  {
    countryKr: "가이아나",
    countryEn: "Guyana",
    capitalKr: "조지타운",
    capitalEn: "Georgetown",
  },
  {
    countryKr: "감비아",
    countryEn: "Gambia",
    capitalKr: "반줄",
    capitalEn: "Banjul",
  },
  {
    countryKr: "과테말라",
    countryEn: "Guatemala",
    capitalKr: "과테말라",
    capitalEn: "Guatemala City",
  },
  {
    countryKr: "그레나다",
    countryEn: "Grenada",
    capitalKr: "세인트조지즈",
    capitalEn: "St. George's",
  },
  {
    countryKr: "그리스",
    countryEn: "Greece",
    capitalKr: "아테네",
    capitalEn: "Athens",
  },
  {
    countryKr: "기니",
    countryEn: "Guinea",
    capitalKr: "코나크리",
    capitalEn: "Conakry",
  },
  {
    countryKr: "기니비사우",
    countryEn: "Guinea-Bissau",
    capitalKr: "비사우",
    capitalEn: "Bissau",
  },
  {
    countryKr: "나미비아",
    countryEn: "Namibia",
    capitalKr: "빈트후크",
    capitalEn: "Windhoek",
  },
  {
    countryKr: "나우루",
    countryEn: "Nauru",
    capitalKr: "야렌",
    capitalEn: "Yaren",
  },
  {
    countryKr: "나이지리아",
    countryEn: "Nigeria",
    capitalKr: "아부자",
    capitalEn: "Abuja",
  },
  {
    countryKr: "남수단",
    countryEn: "South Sudan",
    capitalKr: "주바",
    capitalEn: "Juba",
  },
  {
    countryKr: "남아프리카 공화국",
    countryEn: "South Africa",
    capitalKr: "블룸폰테인(사법), 케이프타운(입법), 프리토리아(행정)",
    capitalEn:
      "Bloemfontein (judicial), Cape Town (legislative), Pretoria (executive)",
  },
  {
    countryKr: "네덜란드",
    countryEn: "Netherlands",
    capitalKr: "암스테르담(공식),헤이그(실질)",
    capitalEn: "Amsterdam (official), The Hague (de facto)",
  },
  {
    countryKr: "네팔",
    countryEn: "Nepal",
    capitalKr: "카트만두",
    capitalEn: "Kathmandu",
  },
  {
    countryKr: "노르웨이",
    countryEn: "Norway",
    capitalKr: "오슬로",
    capitalEn: "Oslo",
  },
  {
    countryKr: "뉴질랜드",
    countryEn: "New Zealand",
    capitalKr: "웰링턴",
    capitalEn: "Wellington",
  },
  {
    countryKr: "니제르",
    countryEn: "Niger",
    capitalKr: "니아메",
    capitalEn: "Niamey",
  },
  {
    countryKr: "니카라과",
    countryEn: "Nicaragua",
    capitalKr: "마나구아",
    capitalEn: "Managua",
  },
  {
    countryKr: "대만",
    countryEn: "Taiwan",
    capitalKr: "타이베이",
    capitalEn: "Taipei",
  },
  {
    countryKr: "대한민국",
    countryEn: "Republic of Korea",
    capitalKr: "서울",
    capitalEn: "Seoul",
  },
  {
    countryKr: "덴마크",
    countryEn: "Denmark",
    capitalKr: "코펜하겐",
    capitalEn: "Copenhagen",
  },
  {
    countryKr: "도미니카 공화국",
    countryEn: "Dominican Republic",
    capitalKr: "산토도밍고",
    capitalEn: "Santo Domingo",
  },
  {
    countryKr: "도미니카 연방",
    countryEn: "Dominica, Commonwealth of…",
    capitalKr: "로조",
    capitalEn: "Roseau",
  },
  {
    countryKr: "독일",
    countryEn: "Germany",
    capitalKr: "베르린",
    capitalEn: "Berlin",
  },
  {
    countryKr: "동티모르",
    countryEn: "Timor-Leste",
    capitalKr: "딜리",
    capitalEn: "Dili",
  },
  {
    countryKr: "라오스",
    countryEn: "Lao People's Democratic Republic",
    capitalKr: "비엔티안",
    capitalEn: "Vientiane",
  },
  {
    countryKr: "라이베리아",
    countryEn: "Liberia",
    capitalKr: "몬로비아",
    capitalEn: "Monrovia",
  },
  {
    countryKr: "라트비아",
    countryEn: "Latvia",
    capitalKr: "리가",
    capitalEn: "Riga",
  },
  {
    countryKr: "러시아",
    countryEn: "Russian Federation",
    capitalKr: "모스크바",
    capitalEn: "Moscow",
  },
  {
    countryKr: "레바논",
    countryEn: "Lebanon",
    capitalKr: "베이루트",
    capitalEn: "Beirut",
  },
  {
    countryKr: "레소토",
    countryEn: "Lesotho",
    capitalKr: "마세루",
    capitalEn: "Maseru",
  },
  {
    countryKr: "루마니아",
    countryEn: "Romania",
    capitalKr: "부쿠레슈티",
    capitalEn: "Bucharest",
  },
  {
    countryKr: "룩셈부르크",
    countryEn: "Luxembourg",
    capitalKr: "룩셈부루크",
    capitalEn: "Luxembourg",
  },
  {
    countryKr: "르완다",
    countryEn: "Rwanda",
    capitalKr: "키칼리",
    capitalEn: "Kigali",
  },
  {
    countryKr: "리비아",
    countryEn: "Libya",
    capitalKr: "트리폴리",
    capitalEn: "Tripoli",
  },
  {
    countryKr: "리투아니아",
    countryEn: "Lithuania",
    capitalKr: "빌뉴스",
    capitalEn: "Vilnius",
  },
  {
    countryKr: "리히텐슈타인",
    countryEn: "Liechtenstein",
    capitalKr: "바두츠",
    capitalEn: "Vaduz",
  },
  {
    countryKr: "마다가스카르",
    countryEn: "Madagascar",
    capitalKr: "안타나나리보",
    capitalEn: "Antananarivo",
  },
  {
    countryKr: "마셜 제도",
    countryEn: "Marshall Islands",
    capitalKr: "마주로",
    capitalEn: "Majuro",
  },
  {
    countryKr: "말라위",
    countryEn: "Malawi",
    capitalKr: "릴롱궤",
    capitalEn: "Lilongwe",
  },
  {
    countryKr: "말레이시아",
    countryEn: "Malaysia",
    capitalKr: "쿠알라룸푸르(공식), 푸트라자야(행정)",
    capitalEn:
      "Kuala Lumpur (official, legislative and royal), Putrajaya (administrative and judicial)",
  },
  {
    countryKr: "말리",
    countryEn: "Mali",
    capitalKr: "바마코",
    capitalEn: "Bamako",
  },
  {
    countryKr: "멕시코",
    countryEn: "Mexico",
    capitalKr: "멕시코시티",
    capitalEn: "Mexico City",
  },
  {
    countryKr: "모나코",
    countryEn: "Monaco",
    capitalKr: "모나코",
    capitalEn: "Monaco",
  },
  {
    countryKr: "모로코",
    countryEn: "Morocco",
    capitalKr: "라바트",
    capitalEn: "Rabat",
  },
  {
    countryKr: "모리셔스",
    countryEn: "Mauritius",
    capitalKr: "포트루이스",
    capitalEn: "Port Louis",
  },
  {
    countryKr: "모리타니",
    countryEn: "Mauritania",
    capitalKr: "누악쇼트",
    capitalEn: "Nouakchott",
  },
  {
    countryKr: "모잠비크",
    countryEn: "Mozambique",
    capitalKr: "마푸토",
    capitalEn: "Maputo",
  },
  {
    countryKr: "몬테네그로",
    countryEn: "Montenegro",
    capitalKr: "포드고리차",
    capitalEn: "Podgorica",
  },
  {
    countryKr: "몰도바",
    countryEn: "Moldova",
    capitalKr: "키시나우",
    capitalEn: "Chișinău",
  },
  {
    countryKr: "몰디브",
    countryEn: "Maldives",
    capitalKr: "말레",
    capitalEn: "Malé",
  },
  {
    countryKr: "몰타",
    countryEn: "Malta",
    capitalKr: "발레타",
    capitalEn: "Valletta",
  },
  {
    countryKr: "몽골",
    countryEn: "Mongolia",
    capitalKr: "울란바토르",
    capitalEn: "Ulaanbaatar",
  },
  {
    countryKr: "미국",
    countryEn: "United States of America",
    capitalKr: "워싱톤",
    capitalEn: "Washington, D.C.",
  },
  {
    countryKr: "미얀마",
    countryEn: "Myanmar",
    capitalKr: "네피도",
    capitalEn: "Naypyidaw",
  },
  {
    countryKr: "미크로네시아 연방",
    countryEn: "Micronesia, Federated States of …",
    capitalKr: "팔라키르",
    capitalEn: "Palikir",
  },
  {
    countryKr: "바누아투",
    countryEn: "Vanuatu",
    capitalKr: "포트 빌라",
    capitalEn: "Port Vila",
  },
  {
    countryKr: "바레인",
    countryEn: "Bahrain",
    capitalKr: "마나마",
    capitalEn: "Manama",
  },
  {
    countryKr: "바베이도스",
    countryEn: "Barbados",
    capitalKr: "브리지타운",
    capitalEn: "Bridgetown",
  },
  {
    countryKr: "바하마",
    countryEn: "Bahamas",
    capitalKr: "나소",
    capitalEn: "Nassau",
  },
  {
    countryKr: "방글라데시",
    countryEn: "Bangladesh",
    capitalKr: "다카",
    capitalEn: "Dhaka",
  },
  {
    countryKr: "베냉",
    countryEn: "Benin",
    capitalKr: "포르토노보",
    capitalEn: "Porto-Novo",
  },
  {
    countryKr: "베네수엘라",
    countryEn: "Venezuela, Bolivarian Republic of...",
    capitalKr: "카라카스",
    capitalEn: "Caracas",
  },
  {
    countryKr: "베트남",
    countryEn: "Viet Nam",
    capitalKr: "하노이",
    capitalEn: "Hanoi",
  },
  {
    countryKr: "벨기에",
    countryEn: "Belgium",
    capitalKr: "브뤼셀",
    capitalEn: "Brussels",
  },
  {
    countryKr: "벨라루스",
    countryEn: "Belarus",
    capitalKr: "민스크",
    capitalEn: "Minsk",
  },
  {
    countryKr: "벨리즈",
    countryEn: "Belize",
    capitalKr: "벨모판",
    capitalEn: "Belmopan",
  },
  {
    countryKr: "보스니아 헤르체고비나",
    countryEn: "Bosnia and Herzegovina",
    capitalKr: "사라예보",
    capitalEn: "Sarajevo",
  },
  {
    countryKr: "보츠와나",
    countryEn: "Botswana",
    capitalKr: "가보로네",
    capitalEn: "Gaborone",
  },
  {
    countryKr: "볼리비아",
    countryEn: "Bolivia",
    capitalKr: "라파스(행정), 수크레(사법)",
    capitalEn: "La Paz (administrative), Sucre (constitutional)",
  },
  {
    countryKr: "부룬디",
    countryEn: "Burundi",
    capitalKr: "기테가(공식), 부줌부라(실질)",
    capitalEn: "Gitega (official), Bujumbura (de facto)",
  },
  {
    countryKr: "부르키나파소",
    countryEn: "Burkina Faso",
    capitalKr: "와가두구",
    capitalEn: "Ouagadougou",
  },
  {
    countryKr: "부탄",
    countryEn: "Bhutan",
    capitalKr: "팀부",
    capitalEn: "Thimphu",
  },
  {
    countryKr: "북마케도니아",
    countryEn: "North Macedonia",
    capitalKr: "스코페",
    capitalEn: "Skopje",
  },
  {
    countryKr: "불가리아",
    countryEn: "Bulgaria",
    capitalKr: "소피아",
    capitalEn: "Sofia",
  },
  {
    countryKr: "브라질",
    countryEn: "Brazil",
    capitalKr: "브라질리아",
    capitalEn: "Brasília",
  },
  {
    countryKr: "브루나이",
    countryEn: "Brunei Darussalam",
    capitalKr: "반다르세리베가완",
    capitalEn: "Bandar Seri Begawan",
  },
  {
    countryKr: "사모아",
    countryEn: "Samoa",
    capitalKr: "아피아",
    capitalEn: "Apia",
  },
  {
    countryKr: "사우디아라비아",
    countryEn: "Saudi Arabia",
    capitalKr: "리야드",
    capitalEn: "Riyadh",
  },
  {
    countryKr: "산마리노",
    countryEn: "San Marino",
    capitalKr: "산마리노",
    capitalEn: "San Marino",
  },
  {
    countryKr: "상투메 프린시페",
    countryEn: "São Tomé and Príncipe",
    capitalKr: "사웅투메",
    capitalEn: "São Tomé",
  },
  {
    countryKr: "세네갈",
    countryEn: "Senegal",
    capitalKr: "다카르",
    capitalEn: "Dakar",
  },
  {
    countryKr: "세르비아",
    countryEn: "Serbia",
    capitalKr: "베오그라드",
    capitalEn: "Belgrade",
  },
  {
    countryKr: "세이셸",
    countryEn: "Seychelles",
    capitalKr: "빅토리아",
    capitalEn: "Victoria",
  },
  {
    countryKr: "세인트루시아",
    countryEn: "Saint Lucia",
    capitalKr: "캐스트리스",
    capitalEn: "Castries",
  },
  {
    countryKr: "세인트빈센트 그레나딘",
    countryEn: "Saint Vincent and the Grenadines",
    capitalKr: "킹스타운",
    capitalEn: "Kingstown",
  },
  {
    countryKr: "세인트키츠 네비스",
    countryEn: "Saint Kitts and Nevis",
    capitalKr: "바스테르",
    capitalEn: "Basseterre",
  },
  {
    countryKr: "소말리아",
    countryEn: "Somalia",
    capitalKr: "모가디슈",
    capitalEn: "Mogadishu",
  },
  {
    countryKr: "솔로몬 제도",
    countryEn: "Solomon Islands",
    capitalKr: "호니아라",
    capitalEn: "Honiara",
  },
  {
    countryKr: "수단",
    countryEn: "Sudan",
    capitalKr: "하르툼",
    capitalEn: "Khartoum",
  },
  {
    countryKr: "수리남",
    countryEn: "Suriname",
    capitalKr: "파라마리보",
    capitalEn: "Paramaribo",
  },
  {
    countryKr: "스리랑카",
    countryEn: "Sri Lanka",
    capitalKr: "스리 자야와르데네푸라 코테(공식), 콜롬보(실질)",
    capitalEn:
      "Sri Jayawardenepura Kotte (official), Colombo (executive, judicial)",
  },
  {
    countryKr: "스웨덴",
    countryEn: "Sweden",
    capitalKr: "스톡홀름",
    capitalEn: "Stockholm",
  },
  {
    countryKr: "스위스",
    countryEn: "Switzerland",
    capitalKr: "베른",
    capitalEn: "Bern",
  },
  {
    countryKr: "스페인",
    countryEn: "Spain",
    capitalKr: "마드리드",
    capitalEn: "Madrid",
  },
  {
    countryKr: "슬로바키아",
    countryEn: "Slovakia",
    capitalKr: "브라티슬라바",
    capitalEn: "Bratislava",
  },
  {
    countryKr: "슬로베니아",
    countryEn: "Slovenia",
    capitalKr: "류블랴나",
    capitalEn: "Ljubljana",
  },
  {
    countryKr: "시리아",
    countryEn: "Syrian Arab Republic",
    capitalKr: "다마스커스",
    capitalEn: "Damascus",
  },
  {
    countryKr: "시에라리온",
    countryEn: "Sierra Leone",
    capitalKr: "프리이타운",
    capitalEn: "Freetown",
  },
  {
    countryKr: "싱가포르",
    countryEn: "Singapore",
    capitalKr: "싱가포르",
    capitalEn: "Singapore",
  },
  {
    countryKr: "아랍에미리트",
    countryEn: "United Arab Emirates",
    capitalKr: "아부다비",
    capitalEn: "Abu Dhabi",
  },
  {
    countryKr: "아르메니아",
    countryEn: "Armenia",
    capitalKr: "예레반",
    capitalEn: "Yerevan",
  },
  {
    countryKr: "아르헨티나",
    countryEn: "Argentina",
    capitalKr: "부에노스아이레스",
    capitalEn: "Buenos Aires",
  },
  {
    countryKr: "아이슬란드",
    countryEn: "Iceland",
    capitalKr: "레이캬비크",
    capitalEn: "Reykjavík",
  },
  {
    countryKr: "아이티",
    countryEn: "Haiti",
    capitalKr: "포르트프랭스",
    capitalEn: "Port-au-Prince",
  },
  {
    countryKr: "아일랜드",
    countryEn: "Ireland",
    capitalKr: "더블린",
    capitalEn: "Dublin",
  },
  {
    countryKr: "아제르바이잔",
    countryEn: "Azerbaijan",
    capitalKr: "바쿠",
    capitalEn: "Baku",
  },
  {
    countryKr: "아프가니스탄",
    countryEn: "Afghanistan",
    capitalKr: "카불",
    capitalEn: "Kabul",
  },
  {
    countryKr: "안도라",
    countryEn: "Andorra",
    capitalKr: "안도라라베야",
    capitalEn: "Andorra la Vella",
  },
  {
    countryKr: "알바니아",
    countryEn: "Albania",
    capitalKr: "티라나",
    capitalEn: "Tirana",
  },
  {
    countryKr: "알제리",
    countryEn: "Algeria",
    capitalKr: "알제",
    capitalEn: "Algiers",
  },
  {
    countryKr: "앙골라",
    countryEn: "Angola",
    capitalKr: "루안다",
    capitalEn: "Luanda",
  },
  {
    countryKr: "앤티가 바부다",
    countryEn: "Antigua and Barbuda",
    capitalKr: "세인트존스",
    capitalEn: "St. John's",
  },
  {
    countryKr: "에리트레아",
    countryEn: "Eritrea",
    capitalKr: "아스마라",
    capitalEn: "Asmara",
  },
  {
    countryKr: "에스와티니",
    countryEn: "Eswatini",
    capitalKr: "로밤바(왕정,입법), 음바바네(행정)",
    capitalEn: "Lobamba (royal and legislative), Mbabane (administrative)",
  },
  {
    countryKr: "에스토니아",
    countryEn: "Estonia",
    capitalKr: "탈린",
    capitalEn: "Tallinn",
  },
  {
    countryKr: "에콰도르",
    countryEn: "Ecuador",
    capitalKr: "키토",
    capitalEn: "Quito",
  },
  {
    countryKr: "에티오피아",
    countryEn: "Ethiopia",
    capitalKr: "아디스아바바",
    capitalEn: "Addis Ababa",
  },
  {
    countryKr: "엘살바도르",
    countryEn: "El Salvador",
    capitalKr: "산살바도르",
    capitalEn: "San Salvador",
  },
  {
    countryKr: "영국",
    countryEn: "United Kingdom of Great Britain and Northern Ireland",
    capitalKr: "런던",
    capitalEn: "London",
  },
  {
    countryKr: "예멘",
    countryEn: "Yemen",
    capitalKr: "사나",
    capitalEn: "Sana'a (de jure), Aden (de facto, temporary)",
  },
  {
    countryKr: "오만",
    countryEn: "Oman",
    capitalKr: "무스카트",
    capitalEn: "Muscat",
  },
  {
    countryKr: "오스트레일리아",
    countryEn: "Australia",
    capitalKr: "캔버라",
    capitalEn: "Canberra",
  },
  {
    countryKr: "오스트리아",
    countryEn: "Austria",
    capitalKr: "빈",
    capitalEn: "Vienna",
  },
  {
    countryKr: "온두라스",
    countryEn: "Honduras",
    capitalKr: "데구시갈파",
    capitalEn: "Tegucigalpa, Comayagüela",
  },
  {
    countryKr: "요르단",
    countryEn: "Jordan",
    capitalKr: "암만",
    capitalEn: "Amman",
  },
  {
    countryKr: "우간다",
    countryEn: "Uganda",
    capitalKr: "캄팔라",
    capitalEn: "Kampala",
  },
  {
    countryKr: "우루과이",
    countryEn: "Uruguay",
    capitalKr: "몬테비데오",
    capitalEn: "Montevideo",
  },
  {
    countryKr: "우즈베키스탄",
    countryEn: "Uzbekistan",
    capitalKr: "타슈켄트",
    capitalEn: "Tashkent",
  },
  {
    countryKr: "우크라이나",
    countryEn: "Ukraine",
    capitalKr: "키이우",
    capitalEn: "Kyiv",
  },
  {
    countryKr: "이라크",
    countryEn: "Iraq",
    capitalKr: "바그다드",
    capitalEn: "Baghdad",
  },
  {
    countryKr: "이란",
    countryEn: "Iran, Islamic Republic of …",
    capitalKr: "테헤란",
    capitalEn: "Tehran",
  },
  {
    countryKr: "이스라엘",
    countryEn: "Israel",
    capitalKr: "예루살렘",
    capitalEn: "Jerusalem",
  },
  {
    countryKr: "이집트",
    countryEn: "Egypt",
    capitalKr: "카이로",
    capitalEn: "Cairo",
  },
  {
    countryKr: "이탈리아",
    countryEn: "Italy",
    capitalKr: "로마",
    capitalEn: "Rome",
  },
  {
    countryKr: "인도",
    countryEn: "India",
    capitalKr: "뉴델리",
    capitalEn: "New Delhi",
  },
  {
    countryKr: "인도네시아",
    countryEn: "Indonesia",
    capitalKr: "자카르타",
    capitalEn: "Jakarta",
  },
  {
    countryKr: "일본",
    countryEn: "Japan",
    capitalKr: "도쿄",
    capitalEn: "Tokyo",
  },
  {
    countryKr: "자메이카",
    countryEn: "Jamaica",
    capitalKr: "킹스턴",
    capitalEn: "Kingston",
  },
  {
    countryKr: "잠비아",
    countryEn: "Zambia",
    capitalKr: "루사카",
    capitalEn: "Lusaka",
  },
  {
    countryKr: "적도 기니",
    countryEn: "Equatorial Guinea",
    capitalKr: "말라보",
    capitalEn: "Malabo",
  },
  {
    countryKr: "조선민주주의인민공화국",
    countryEn: "Democratic People's Republic of Korea",
    capitalKr: "평양",
    capitalEn: "Pyongyang",
  },
  {
    countryKr: "조지아",
    countryEn: "Georgia",
    capitalKr: "트빌리시",
    capitalEn: "Tbilisi",
  },
  {
    countryKr: "중앙아프리카 공화국",
    countryEn: "Central African Republic",
    capitalKr: "방기",
    capitalEn: "Bangui",
  },
  {
    countryKr: "중화인민공화국",
    countryEn: "China",
    capitalKr: "베이징",
    capitalEn: "Beijing",
  },
  {
    countryKr: "지부티",
    countryEn: "Djibouti",
    capitalKr: "지부티",
    capitalEn: "Djibouti",
  },
  {
    countryKr: "짐바브웨",
    countryEn: "Zimbabwe",
    capitalKr: "하라레",
    capitalEn: "Harare",
  },
  {
    countryKr: "차드",
    countryEn: "Chad",
    capitalKr: "엔자메나",
    capitalEn: "N'Djamena",
  },
  {
    countryKr: "체코",
    countryEn: "Czech Republic",
    capitalKr: "프라하",
    capitalEn: "Prague",
  },
  {
    countryKr: "칠레",
    countryEn: "Chile",
    capitalKr: "산티아고",
    capitalEn: "Santiago",
  },
  {
    countryKr: "카메룬",
    countryEn: "Cameroon",
    capitalKr: "야운데",
    capitalEn: "Yaoundé",
  },
  {
    countryKr: "카보베르데",
    countryEn: "Cape Verde",
    capitalKr: "프라이야",
    capitalEn: "Praia",
  },
  {
    countryKr: "카자흐스탄",
    countryEn: "Kazakhstan",
    capitalKr: "아스타나",
    capitalEn: "Astana",
  },
  {
    countryKr: "카타르",
    countryEn: "Qatar",
    capitalKr: "도하",
    capitalEn: "Doha",
  },
  {
    countryKr: "캄보디아",
    countryEn: "Cambodia",
    capitalKr: "프놈펜",
    capitalEn: "Phnom Penh",
  },
  {
    countryKr: "캐나다",
    countryEn: "Canada",
    capitalKr: "오타와",
    capitalEn: "Ottawa",
  },
  {
    countryKr: "케냐",
    countryEn: "Kenya",
    capitalKr: "나이로비",
    capitalEn: "Nairobi",
  },
  {
    countryKr: "코모로",
    countryEn: "Comoros",
    capitalKr: "모로니",
    capitalEn: "Moroni",
  },
  {
    countryKr: "코스타리카",
    countryEn: "Costa Rica",
    capitalKr: "산호세",
    capitalEn: "San José",
  },
  {
    countryKr: "코트디부아르",
    countryEn: "Côte d'Ivoire",
    capitalKr: "야무스크로",
    capitalEn: "Yamoussoukro",
  },
  {
    countryKr: "콜롬비아",
    countryEn: "Colombia",
    capitalKr: "보고타",
    capitalEn: "Bogotá",
  },
  {
    countryKr: "콩고 공화국",
    countryEn: "Congo",
    capitalKr: "브라자빌",
    capitalEn: "Brazzaville",
  },
  {
    countryKr: "콩고 민주 공화국",
    countryEn: "Democratic Republic of the Congo",
    capitalKr: "킨샤샤",
    capitalEn: "Kinshasa",
  },
  {
    countryKr: "쿠바",
    countryEn: "Cuba",
    capitalKr: "하바나",
    capitalEn: "Havana",
  },
  {
    countryKr: "쿠웨이트",
    countryEn: "Kuwait",
    capitalKr: "쿠웨이트",
    capitalEn: "Kuwait City",
  },
  {
    countryKr: "크로아티아",
    countryEn: "Croatia",
    capitalKr: "자그레브",
    capitalEn: "Zagreb",
  },
  {
    countryKr: "키르기스스탄",
    countryEn: "Kyrgyzstan",
    capitalKr: "비슈케크",
    capitalEn: "Bishkek",
  },
  {
    countryKr: "키리바시",
    countryEn: "Kiribati",
    capitalKr: "사우스타라와",
    capitalEn: "South Tarawa",
  },
  {
    countryKr: "키프로스",
    countryEn: "Cyprus",
    capitalKr: "니코시아",
    capitalEn: "Nicosia",
  },
  {
    countryKr: "타지키스탄",
    countryEn: "Tajikistan",
    capitalKr: "두샨베",
    capitalEn: "Dushanbe",
  },
  {
    countryKr: "탄자니아",
    countryEn: "United Republic of Tanzania",
    capitalKr: "도도마(공식), 다르에스살람(실질)",
    capitalEn:
      "Dodoma (official, legislative), Dar es Salaam (de facto, judicial)",
  },
  {
    countryKr: "태국",
    countryEn: "Thailand",
    capitalKr: "방콕",
    capitalEn: "Bangkok",
  },
  {
    countryKr: "토고",
    countryEn: "Togo",
    capitalKr: "로메",
    capitalEn: "Lomé",
  },
  {
    countryKr: "통가",
    countryEn: "Tonga",
    capitalKr: "누쿠알로파",
    capitalEn: "Nukuʻalofa",
  },
  {
    countryKr: "투르크메니스탄",
    countryEn: "Turkmenistan",
    capitalKr: "아슈하바트",
    capitalEn: "Ashgabat",
  },
  {
    countryKr: "투발루",
    countryEn: "Tuvalu",
    capitalKr: "푸나푸티",
    capitalEn: "Funafuti",
  },
  {
    countryKr: "튀니지",
    countryEn: "Tunisia",
    capitalKr: "튀니스",
    capitalEn: "Tunis",
  },
  {
    countryKr: "튀르키예",
    countryEn: "Türkiye",
    capitalKr: "앙카라",
    capitalEn: "Ankara",
  },
  {
    countryKr: "트리니다드 토바고",
    countryEn: "Trinidad and Tobago",
    capitalKr: "포오트오브스페인",
    capitalEn: "Port of Spain",
  },
  {
    countryKr: "파나마",
    countryEn: "Panama",
    capitalKr: "파나마",
    capitalEn: "Panama City",
  },
  {
    countryKr: "파라과이",
    countryEn: "Paraguay",
    capitalKr: "아순시온",
    capitalEn: "Asunción",
  },
  {
    countryKr: "파키스탄",
    countryEn: "Pakistan",
    capitalKr: "이슬라마바드",
    capitalEn: "Islamabad",
  },
  {
    countryKr: "파푸아뉴기니",
    countryEn: "Papua New Guinea",
    capitalKr: "포트모르즈비",
    capitalEn: "Port Moresby",
  },
  {
    countryKr: "팔라우",
    countryEn: "Palau",
    capitalKr: "응게룰무드",
    capitalEn: "Ngerulmud",
  },
  {
    countryKr: "페루",
    countryEn: "Peru",
    capitalKr: "리마",
    capitalEn: "Lima",
  },
  {
    countryKr: "포르투갈",
    countryEn: "Portugal",
    capitalKr: "리스본",
    capitalEn: "Lisbon",
  },
  {
    countryKr: "폴란드",
    countryEn: "Poland",
    capitalKr: "바르샤바",
    capitalEn: "Warsaw",
  },
  {
    countryKr: "프랑스",
    countryEn: "France",
    capitalKr: "파리",
    capitalEn: "Paris",
  },
  {
    countryKr: "피지",
    countryEn: "Fiji",
    capitalKr: "수바",
    capitalEn: "Suva",
  },
  {
    countryKr: "핀란드",
    countryEn: "Finland",
    capitalKr: "헬싱키",
    capitalEn: "Helsinki",
  },
  {
    countryKr: "필리핀",
    countryEn: "Philippines",
    capitalKr: "마닐라",
    capitalEn: "Manila",
  },
  {
    countryKr: "헝가리",
    countryEn: "Hungary",
    capitalKr: "부다페스트",
    capitalEn: "Budapest",
  },
  {
    countryKr: "홍콩",
    countryEn: "Hong Kong",
    capitalKr: "특별행정구",
    capitalEn: "-",
  },
];
